export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const NUMBER_USER = "NUMBER_USER";
export const ALL_USER_DATA = "ALL_USER_DATA";
export const ALL_PARKING_NEED_VERIFIED = "ALL_PARKING_NEED_VERIFIED";
